---
title: "Leptin Gene Signature (LGS) Derivation"
output: html_notebook
---

```{r setup}
library(DESeq2)
library(tidyverse)
library(mixOmics)
library(clusterProfiler)
library(org.Mm.eg.db)

set.seed(42)

data_dir <- "../external_data"
out_dir <- "../output_figures/paper/lgs"
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
```

Dataset 1: GSE162603 (Allison et al. 2020) - sTRAP leptin vs fasted, controlling for time
```{r dataset1_trap}
countmat <- read.csv(file.path(data_dir, "GSE162603_counts.csv.gz")) %>%
  filter(!duplicated(gene_name))
cts <- countmat[, c(3:ncol(countmat))]
rownames(cts) <- countmat$gene_name

meta <- read.csv(file.path(data_dir, "GSE162603_metadata.csv.gz"))
rownames(meta) <- colnames(cts)
meta$group <- ifelse(grepl("Leptin", meta$Treatment), "leptin", "fasted")
meta$time <- ifelse(grepl("10", meta$Treatment), "10", "3")
meta$animal <- substr(meta$Description, start = 1, stop = 2)

dds <- DESeqDataSetFromMatrix(countData = cts[, meta$Cells == "Bead"],
                              colData = meta[meta$Cells == "Bead", ],
                              design = ~group + time)

keep <- rowSums(counts(dds) >= 10) >= 3
dds <- dds[keep, ]
dds <- DESeq(dds, test = "LRT", reduced = ~time)
vsd_trap <- vst(dds, blind = FALSE)
```

Dataset 2: Heyward et al. - AgRP neuron bulk RNA-seq, leptin vs fasted
```{r dataset2_agrp}
load(file.path(data_dir, "dea-rna/data.Robject"))
dds_agrp <- DESeqDataSetFromMatrix(
  countData = data_edger$counts[, data_edger$samples$group != "fed"],
  colData = data_edger$samples[data_edger$samples$group != "fed", ],
  design = ~group)

keep <- rowSums(counts(dds_agrp) >= 10) >= 3
dds_agrp <- dds_agrp[keep, ]
dds_agrp <- DESeq(dds_agrp)
vsd_agrp <- vst(dds_agrp, blind = FALSE)
```

Dataset 3: GSE112125 (Inoue et al. 2019) - LepR neuron leptin RNA, pre-normalized
```{r dataset3_ahituv}
ahituv_data <- readxl::read_excel(file.path(data_dir, "GSE112125_All_genes.Leptin_RNA.xlsx"))
vsd_ahit <- ahituv_data %>%
  dplyr::select(c(ends_with("Gene"), contains("stabilized"))) %>%
  filter(!duplicated(Gene)) %>%
  column_to_rownames("Gene") %>%
  dplyr::select(contains("GFPp"))
meta_ahit <- ifelse(grepl("L", colnames(vsd_ahit)), "leptin", "fasted")
```

MINT sPLS-DA: cross-study integration to derive leptin gene signature
```{r mint_splsda}
X <- merge(assay(vsd_trap) %>% data.frame() %>% rownames_to_column("gene"),
           assay(vsd_agrp) %>% data.frame() %>% rownames_to_column("gene"), by = "gene") %>%
  merge(., vsd_ahit %>% rownames_to_column("gene"), by = "gene") %>%
  column_to_rownames("gene")

y <- c(colData(vsd_trap)$group, colData(vsd_agrp)$group, factor(meta_ahit))
study <- c(rep("trap", ncol(assay(vsd_trap))),
           rep("agrp", ncol(assay(vsd_agrp))),
           rep("ahit", ncol(vsd_ahit)))

basic.splsda.model <- mint.splsda(t(X), y, study = study,
                                   ncomp = 2, keepX = 100,
                                   near.zero.var = TRUE, scale = FALSE)

plotIndiv(basic.splsda.model, legend = TRUE,
          title = '', subtitle = 'Leptin Treatment', ellipse = TRUE)
ggsave(file.path(out_dir, "lgs_splsda.pdf"), h = 3, w = 6)
```

Extract LGS genes and GO enrichment
```{r lgs_output}
# Export all selected genes with loadings
selectVar(basic.splsda.model)$value %>%
  rownames_to_column("gene") %>%
  write_csv(file.path(out_dir, "lgs_genes.csv"))

# Top 25 by absolute loading weight
selectVar(basic.splsda.model)$value %>%
  rownames_to_column("gene") %>%
  dplyr::slice_max(n = 25, order_by = abs(value.var)) %>%
  ggplot() +
  aes(x = fct_reorder(gene, value.var), y = value.var) +
  geom_col() +
  labs(y = "Model Weight", x = NULL) +
  cowplot::theme_cowplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(file.path(out_dir, "lgs_barplot.pdf"), h = 3, w = 5)

# GO enrichment on leptin-downregulated genes (negative loadings)
markers <- rownames(selectVar(basic.splsda.model)$value)[selectVar(basic.splsda.model)$value < 0]
go_lgs <- enrichGO(markers, OrgDb = "org.Mm.eg.db", ont = "ALL",
                   keyType = "SYMBOL", universe = rownames(X))
go_lgs_simple <- simplify(go_lgs, cutoff = 0.5, by = "p.adjust", select_fun = min)
barplot(go_lgs_simple, show = 5) + theme(axis.text.y = element_text(size = 6))
ggsave(file.path(out_dir, "lgs_go.pdf"), h = 4, w = 5)

go_lgs_simple@result %>% write_csv(file.path(out_dir, "goterm_enrich_lgs.csv"))
```
